using NUnit.Framework;
using TestGenerator.Core;

namespace TestGenerator.UnitTests;

[TestFixture]
public sealed class TestGeneratorServiceTests
{
    [Test]
    public async Task GenerateAsync_SplitsOneFileIntoOneTestClassPerPublicType()
    {
        string source = """
            using System;

            namespace Sample
            {
                public class Foo
                {
                    public void A() { }
                }

                public class Bar
                {
                    public void B() { }
                }
            }
            """;
        await using TempDirectoryFixture temp = await TempDirectoryFixture.CreateAsync();
        string inputPath = Path.Combine(temp.RootPath, "Input.cs");
        await File.WriteAllTextAsync(inputPath, source).ConfigureAwait(false);
        GeneratorOptions options = CreateOptions(
            new[] { inputPath },
            temp.OutputPath,
            useAdvanced: false);
        await TestGeneratorService.GenerateAsync(options).ConfigureAwait(false);
        string fooPath = Path.Combine(temp.OutputPath, "FooTests.cs");
        string barPath = Path.Combine(temp.OutputPath, "BarTests.cs");
        Assert.That(File.Exists(fooPath), Is.True);
        Assert.That(File.Exists(barPath), Is.True);
        string fooText = await File.ReadAllTextAsync(fooPath).ConfigureAwait(false);
        Assert.That(fooText, Does.Contain("public void ATest"));
        Assert.That(fooText, Does.Contain("Assert.Fail(\"autogenerated\")"));
    }

    [Test]
    public async Task GenerateAsync_NumbersOverloadTestNames()
    {
        string source = """
            namespace Sample
            {
                public class C
                {
                    public void M(int x) { }
                    public void M(double x) { }
                }
            }
            """;
        await using TempDirectoryFixture temp = await TempDirectoryFixture.CreateAsync();
        string inputPath = Path.Combine(temp.RootPath, "Input.cs");
        await File.WriteAllTextAsync(inputPath, source).ConfigureAwait(false);
        GeneratorOptions options = CreateOptions(
            new[] { inputPath },
            temp.OutputPath,
            useAdvanced: false);
        await TestGeneratorService.GenerateAsync(options).ConfigureAwait(false);
        string text = await File.ReadAllTextAsync(Path.Combine(temp.OutputPath, "CTests.cs")).ConfigureAwait(false);
        Assert.That(text, Does.Contain("public void M1Test"));
        Assert.That(text, Does.Contain("public void M2Test"));
    }

    [Test]
    public async Task GenerateAsync_AdvancedModeAddsMocksAndSetUp()
    {
        string source = """
            namespace Sample
            {
                public interface IDependency { }

                public class Sut
                {
                    public Sut(IDependency dependency) { }

                    public int Run(int value) => value;
                }
            }
            """;
        await using TempDirectoryFixture temp = await TempDirectoryFixture.CreateAsync();
        string inputPath = Path.Combine(temp.RootPath, "Input.cs");
        await File.WriteAllTextAsync(inputPath, source).ConfigureAwait(false);
        GeneratorOptions options = CreateOptions(
            new[] { inputPath },
            temp.OutputPath,
            useAdvanced: true);
        await TestGeneratorService.GenerateAsync(options).ConfigureAwait(false);
        string text = await File.ReadAllTextAsync(Path.Combine(temp.OutputPath, "SutTests.cs")).ConfigureAwait(false);
        Assert.That(text, Does.Contain("using Moq;"));
        Assert.That(text, Does.Contain("Mock<IDependency>"));
        Assert.That(text, Does.Contain("[SetUp]"));
        Assert.That(text, Does.Contain("Assert.That(actual, Is.EqualTo(expected))"));
        Assert.That(text, Does.Contain("Assert.Fail(\"autogenerated\")"));
    }

    private static GeneratorOptions CreateOptions(
        string[] inputFiles,
        string outputDirectory,
        bool useAdvanced)
    {
        return new GeneratorOptions(
            inputFiles,
            outputDirectory,
            MaxConcurrentReads: 2,
            MaxConcurrentGeneration: 2,
            MaxConcurrentWrites: 2,
            useAdvanced);
    }

    private sealed class TempDirectoryFixture : IAsyncDisposable
    {
        private TempDirectoryFixture(string rootPath, string outputPath)
        {
            RootPath = rootPath;
            OutputPath = outputPath;
        }

        internal string RootPath { get; }

        internal string OutputPath { get; }

        internal static Task<TempDirectoryFixture> CreateAsync()
        {
            string root = Path.Combine(Path.GetTempPath(), "tg-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(root);
            string output = Path.Combine(root, "out");
            return Task.FromResult(new TempDirectoryFixture(root, output));
        }

        public ValueTask DisposeAsync()
        {
            if (!Directory.Exists(RootPath))
            {
                return ValueTask.CompletedTask;
            }
            try
            {
                Directory.Delete(RootPath, recursive: true);
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
            return ValueTask.CompletedTask;
        }
    }
}
