using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TestGenerator.Core.Advanced;
using TestGenerator.Core.Analysis;
using TestGenerator.Core.Pipeline;

namespace TestGenerator.Core.Generation;

internal static class TestCompilationUnitGenerator
{
    internal static TestFile Generate(WorkItem workItem, GeneratorOptions options)
    {
        ClassDeclarationSyntax classSyntax = workItem.ClassSyntax;
        string testsNamespace = ClassExtractor.GetTestsNamespace(workItem);
        string originalNamespace = ClassExtractor.GetOriginalNamespace(workItem);
        string testClassName = ClassExtractor.GetTestClassName(classSyntax);
        IReadOnlyList<MethodOverloadNaming.PublicMethodInfo> methods = MethodOverloadNaming.BuildPublicMethodInfos(classSyntax);
        List<MemberDeclarationSyntax> members = new List<MemberDeclarationSyntax>();
        ConstructorPlan? constructorPlan = null;
        if (options.UseAdvancedDependencySetup)
        {
            constructorPlan = ConstructorPlan.Create(classSyntax);
            members.AddRange(constructorPlan.BuildFieldDeclarations());
            members.Add(constructorPlan.BuildInitializationMember());
        }
        string? subjectFieldName = constructorPlan?.SubjectFieldName;
        foreach (MethodOverloadNaming.PublicMethodInfo methodInfo in methods)
        {
            members.Add(BuildTestMethod(methodInfo, classSyntax, options, subjectFieldName));
        }
        ClassDeclarationSyntax testClassDeclaration = SyntaxFactory.ClassDeclaration(testClassName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithMembers(SyntaxFactory.List(members));
        testClassDeclaration = testClassDeclaration.AddAttributeLists(
            SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("TestFixture")))));
        NamespaceDeclarationSyntax namespaceDeclaration = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(testsNamespace))
            .WithMembers(SyntaxFactory.SingletonList<MemberDeclarationSyntax>(testClassDeclaration));
        CompilationUnitSyntax compilationUnit = SyntaxFactory.CompilationUnit()
            .WithUsings(BuildUsingDirectives(originalNamespace, constructorPlan))
            .WithMembers(SyntaxFactory.SingletonList<MemberDeclarationSyntax>(namespaceDeclaration))
            .NormalizeWhitespace();
        StringBuilder textBuilder = new StringBuilder();
        textBuilder.AppendLine(compilationUnit.ToFullString());
        return new TestFile(ClassExtractor.GetOutputFileName(classSyntax), textBuilder.ToString());
    }

    private static SyntaxList<UsingDirectiveSyntax> BuildUsingDirectives(
        string originalNamespace,
        ConstructorPlan? constructorPlan)
    {
        List<UsingDirectiveSyntax> usings = new List<UsingDirectiveSyntax>
        {
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Collections.Generic")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Linq")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Text"))
        };
        usings.Add(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("NUnit.Framework")));
        if (constructorPlan is not null && constructorPlan.RequiresMock)
        {
            usings.Add(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Moq")));
        }
        if (!string.Equals(originalNamespace, "Global", StringComparison.Ordinal))
        {
            usings.Add(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(originalNamespace)));
        }
        return SyntaxFactory.List(usings);
    }

    private static MemberDeclarationSyntax BuildTestMethod(
        MethodOverloadNaming.PublicMethodInfo methodInfo,
        ClassDeclarationSyntax classSyntax,
        GeneratorOptions options,
        string? subjectFieldName)
    {
        MethodDeclarationSyntax targetMethod = methodInfo.Method;
        string methodName = methodInfo.TestMethodName;
        if (!options.UseAdvancedDependencySetup || subjectFieldName is null)
        {
            return BuildBasicTestMethod(methodName);
        }
        return BuildAdvancedTestMethod(targetMethod, classSyntax, methodName, subjectFieldName);
    }

    private static MemberDeclarationSyntax BuildBasicTestMethod(string methodName)
    {
        BlockSyntax body = SyntaxFactory.Block(SyntaxFactory.SingletonList(CreateAutogeneratedFailStatement()));
        return SyntaxFactory.MethodDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)), methodName)
            .AddModifiers(
                SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithAttributeLists(GetNUnitTestAttributeList())
            .WithBody(body);
    }

    private static MemberDeclarationSyntax BuildAdvancedTestMethod(
        MethodDeclarationSyntax targetMethod,
        ClassDeclarationSyntax classSyntax,
        string testMethodName,
        string subjectFieldName)
    {
        BlockSyntax body = BuildAdvancedMethodBody(targetMethod, classSyntax, subjectFieldName);
        return SyntaxFactory.MethodDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)), testMethodName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithAttributeLists(GetNUnitTestAttributeList())
            .WithBody(body);
    }

    private static BlockSyntax BuildAdvancedMethodBody(
        MethodDeclarationSyntax targetMethod,
        ClassDeclarationSyntax classSyntax,
        string subjectFieldName)
    {
        List<StatementSyntax> statements = new List<StatementSyntax>();
        IReadOnlyList<ParameterSyntax> parameters = targetMethod.ParameterList.Parameters.ToList();
        foreach (ParameterSyntax parameter in parameters)
        {
            TypeSyntax parameterType = parameter.Type ?? SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.ObjectKeyword));
            VariableDeclarationSyntax declaration = SyntaxFactory.VariableDeclaration(parameterType)
                .AddVariables(SyntaxFactory.VariableDeclarator(parameter.Identifier)
                    .WithInitializer(SyntaxFactory.EqualsValueClause(DefaultParameterValueSyntaxFactory.CreateDefaultValueForType(parameterType))));
            statements.Add(SyntaxFactory.LocalDeclarationStatement(declaration));
        }
        TypeSyntax? returnType = targetMethod.ReturnType;
        bool isVoid = returnType is PredefinedTypeSyntax predefined && predefined.Keyword.IsKind(SyntaxKind.VoidKeyword);
        ExpressionSyntax invocationTarget = BuildInvocationTargetExpression(targetMethod, classSyntax, subjectFieldName);
        ArgumentListSyntax argumentList = SyntaxFactory.ArgumentList(SyntaxFactory.SeparatedList(
            parameters.Select(p => SyntaxFactory.Argument(SyntaxFactory.IdentifierName(p.Identifier)))));
        InvocationExpressionSyntax invocation = SyntaxFactory.InvocationExpression(
            SyntaxFactory.MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                invocationTarget,
                SyntaxFactory.IdentifierName(targetMethod.Identifier)),
            argumentList);
        if (isVoid)
        {
            statements.Add(SyntaxFactory.ExpressionStatement(invocation));
        }
        else
        {
            VariableDeclarationSyntax actualDeclaration = SyntaxFactory.VariableDeclaration(returnType!)
                .AddVariables(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("actual"))
                    .WithInitializer(SyntaxFactory.EqualsValueClause(invocation)));
            statements.Add(SyntaxFactory.LocalDeclarationStatement(actualDeclaration));
            TypeSyntax expectedType = returnType!;
            VariableDeclarationSyntax expectedDeclaration = SyntaxFactory.VariableDeclaration(expectedType)
                .AddVariables(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("expected"))
                    .WithInitializer(SyntaxFactory.EqualsValueClause(DefaultParameterValueSyntaxFactory.CreateDefaultValueForType(expectedType))));
            statements.Add(SyntaxFactory.LocalDeclarationStatement(expectedDeclaration));
            statements.Add(CreateEqualityAssertionStatement());
        }
        statements.Add(CreateAutogeneratedFailStatement());
        return SyntaxFactory.Block(SyntaxFactory.List(statements));
    }

    private static ExpressionSyntax BuildInvocationTargetExpression(
        MethodDeclarationSyntax targetMethod,
        ClassDeclarationSyntax classSyntax,
        string subjectFieldName)
    {
        if (targetMethod.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword)))
        {
            return SyntaxFactory.IdentifierName(classSyntax.Identifier);
        }
        return SyntaxFactory.IdentifierName(subjectFieldName);
    }

    private static StatementSyntax CreateEqualityAssertionStatement()
    {
        return SyntaxFactory.ParseStatement("Assert.That(actual, Is.EqualTo(expected));");
    }

    private static StatementSyntax CreateAutogeneratedFailStatement()
    {
        return SyntaxFactory.ParseStatement("Assert.Fail(\"autogenerated\");");
    }

    private static SyntaxList<AttributeListSyntax> GetNUnitTestAttributeList()
    {
        return SyntaxFactory.SingletonList(
            SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Test")))));
    }
}
