using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TestGenerator.Core.Analysis;
using TestGenerator.Core.Pipeline;

namespace TestGenerator.Core.Generation;

internal static class TestCompilationUnitGenerator
{
    internal static TestFile Generate(WorkItem workItem, GeneratorOptions options)
    {
        ClassDeclarationSyntax classSyntax = workItem.ClassSyntax;
        string testsNamespace = ClassExtractor.GetTestsNamespace(workItem);
        string originalNamespace = ClassExtractor.GetOriginalNamespace(workItem);
        string testClassName = ClassExtractor.GetTestClassName(classSyntax);
        IReadOnlyList<MethodOverloadNaming.PublicMethodInfo> methods = MethodOverloadNaming.BuildPublicMethodInfos(classSyntax);
        List<MemberDeclarationSyntax> members = new List<MemberDeclarationSyntax>();
        ConstructorPlan? constructorPlan = null;
        if (options.UseAdvancedDependencySetup)
        {
            constructorPlan = ConstructorPlan.Create(classSyntax);
            members.AddRange(constructorPlan.BuildFieldDeclarations());
            members.Add(constructorPlan.BuildInitializationMember());
        }
        string? subjectFieldName = constructorPlan?.SubjectFieldName;
        foreach (MethodOverloadNaming.PublicMethodInfo methodInfo in methods)
        {
            members.Add(BuildTestMethod(methodInfo, classSyntax, options, subjectFieldName));
        }
        ClassDeclarationSyntax testClassDeclaration = SyntaxFactory.ClassDeclaration(testClassName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithMembers(SyntaxFactory.List(members));
        testClassDeclaration = testClassDeclaration.AddAttributeLists(
            SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("TestFixture")))));
        NamespaceDeclarationSyntax namespaceDeclaration = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(testsNamespace))
            .WithMembers(SyntaxFactory.SingletonList<MemberDeclarationSyntax>(testClassDeclaration));
        CompilationUnitSyntax compilationUnit = SyntaxFactory.CompilationUnit()
            .WithUsings(BuildUsingDirectives(originalNamespace, constructorPlan))
            .WithMembers(SyntaxFactory.SingletonList<MemberDeclarationSyntax>(namespaceDeclaration))
            .NormalizeWhitespace();
        StringBuilder textBuilder = new StringBuilder();
        textBuilder.AppendLine(compilationUnit.ToFullString());
        return new TestFile(ClassExtractor.GetOutputFileName(classSyntax), textBuilder.ToString());
    }

    private static SyntaxList<UsingDirectiveSyntax> BuildUsingDirectives(
        string originalNamespace,
        ConstructorPlan? constructorPlan)
    {
        List<UsingDirectiveSyntax> usings = new List<UsingDirectiveSyntax>
        {
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Collections.Generic")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Linq")),
            SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("System.Text"))
        };
        usings.Add(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("NUnit.Framework")));
        if (constructorPlan is not null && constructorPlan.RequiresMock)
        {
            usings.Add(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName("Moq")));
        }
        if (!string.Equals(originalNamespace, "Global", StringComparison.Ordinal))
        {
            usings.Add(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(originalNamespace)));
        }
        return SyntaxFactory.List(usings);
    }

    private static MemberDeclarationSyntax BuildTestMethod(
        MethodOverloadNaming.PublicMethodInfo methodInfo,
        ClassDeclarationSyntax classSyntax,
        GeneratorOptions options,
        string? subjectFieldName)
    {
        MethodDeclarationSyntax targetMethod = methodInfo.Method;
        string methodName = methodInfo.TestMethodName;
        if (!options.UseAdvancedDependencySetup || subjectFieldName is null)
        {
            return BuildBasicTestMethod(methodName);
        }
        return BuildAdvancedTestMethod(targetMethod, classSyntax, methodName, subjectFieldName);
    }

    private static MemberDeclarationSyntax BuildBasicTestMethod(string methodName)
    {
        BlockSyntax body = SyntaxFactory.Block(SyntaxFactory.SingletonList(CreateAutogeneratedFailStatement()));
        return SyntaxFactory.MethodDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)), methodName)
            .AddModifiers(
                SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithAttributeLists(GetNUnitTestAttributeList())
            .WithBody(body);
    }

    private static MemberDeclarationSyntax BuildAdvancedTestMethod(
        MethodDeclarationSyntax targetMethod,
        ClassDeclarationSyntax classSyntax,
        string testMethodName,
        string subjectFieldName)
    {
        BlockSyntax body = BuildAdvancedMethodBody(targetMethod, classSyntax, subjectFieldName);
        return SyntaxFactory.MethodDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)), testMethodName)
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .WithAttributeLists(GetNUnitTestAttributeList())
            .WithBody(body);
    }

    private static BlockSyntax BuildAdvancedMethodBody(
        MethodDeclarationSyntax targetMethod,
        ClassDeclarationSyntax classSyntax,
        string subjectFieldName)
    {
        List<StatementSyntax> statements = new List<StatementSyntax>();
        IReadOnlyList<ParameterSyntax> parameters = targetMethod.ParameterList.Parameters.ToList();
        foreach (ParameterSyntax parameter in parameters)
        {
            TypeSyntax parameterType = parameter.Type ?? SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.ObjectKeyword));
            VariableDeclarationSyntax declaration = SyntaxFactory.VariableDeclaration(parameterType)
                .AddVariables(SyntaxFactory.VariableDeclarator(parameter.Identifier)
                    .WithInitializer(SyntaxFactory.EqualsValueClause(DefaultParameterValueSyntaxFactory.CreateDefaultValueForType(parameterType))));
            statements.Add(SyntaxFactory.LocalDeclarationStatement(declaration));
        }
        TypeSyntax? returnType = targetMethod.ReturnType;
        bool isVoid = returnType is PredefinedTypeSyntax predefined && predefined.Keyword.IsKind(SyntaxKind.VoidKeyword);
        ExpressionSyntax invocationTarget = BuildInvocationTargetExpression(targetMethod, classSyntax, subjectFieldName);
        ArgumentListSyntax argumentList = SyntaxFactory.ArgumentList(SyntaxFactory.SeparatedList(
            parameters.Select(p => SyntaxFactory.Argument(SyntaxFactory.IdentifierName(p.Identifier)))));
        InvocationExpressionSyntax invocation = SyntaxFactory.InvocationExpression(
            SyntaxFactory.MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                invocationTarget,
                SyntaxFactory.IdentifierName(targetMethod.Identifier)),
            argumentList);
        if (isVoid)
        {
            statements.Add(SyntaxFactory.ExpressionStatement(invocation));
        }
        else
        {
            VariableDeclarationSyntax actualDeclaration = SyntaxFactory.VariableDeclaration(returnType!)
                .AddVariables(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("actual"))
                    .WithInitializer(SyntaxFactory.EqualsValueClause(invocation)));
            statements.Add(SyntaxFactory.LocalDeclarationStatement(actualDeclaration));
            TypeSyntax expectedType = returnType!;
            VariableDeclarationSyntax expectedDeclaration = SyntaxFactory.VariableDeclaration(expectedType)
                .AddVariables(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier("expected"))
                    .WithInitializer(SyntaxFactory.EqualsValueClause(DefaultParameterValueSyntaxFactory.CreateDefaultValueForType(expectedType))));
            statements.Add(SyntaxFactory.LocalDeclarationStatement(expectedDeclaration));
            statements.Add(CreateEqualityAssertionStatement());
        }
        statements.Add(CreateAutogeneratedFailStatement());
        return SyntaxFactory.Block(SyntaxFactory.List(statements));
    }

    private static ExpressionSyntax BuildInvocationTargetExpression(
        MethodDeclarationSyntax targetMethod,
        ClassDeclarationSyntax classSyntax,
        string subjectFieldName)
    {
        if (targetMethod.Modifiers.Any(m => m.IsKind(SyntaxKind.StaticKeyword)))
        {
            return SyntaxFactory.IdentifierName(classSyntax.Identifier);
        }
        return SyntaxFactory.IdentifierName(subjectFieldName);
    }

    private static StatementSyntax CreateEqualityAssertionStatement()
    {
        return SyntaxFactory.ParseStatement("Assert.That(actual, Is.EqualTo(expected));");
    }

    private static StatementSyntax CreateAutogeneratedFailStatement()
    {
        return SyntaxFactory.ParseStatement("Assert.Fail(\"autogenerated\");");
    }

    private static SyntaxList<AttributeListSyntax> GetNUnitTestAttributeList()
    {
        return SyntaxFactory.SingletonList(
            SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("Test")))));
    }

    private sealed class ConstructorPlan
    {
        private ConstructorPlan(ClassDeclarationSyntax classSyntax, string subjectFieldName, IReadOnlyList<ConstructorParameterBinding> parameters)
        {
            ClassSyntax = classSyntax;
            SubjectFieldName = subjectFieldName;
            Parameters = parameters;
        }

        internal ClassDeclarationSyntax ClassSyntax { get; }

        internal string SubjectFieldName { get; }

        internal IReadOnlyList<ConstructorParameterBinding> Parameters { get; }

        internal bool RequiresMock => Parameters.Any(p => p.IsInterface);

        internal static ConstructorPlan Create(ClassDeclarationSyntax classSyntax)
        {
            string className = classSyntax.Identifier.ValueText;
            string subjectField = BuildSubjectFieldName(className);
            ConstructorDeclarationSyntax? ctor = classSyntax.Members
                .OfType<ConstructorDeclarationSyntax>()
                .Where(c => c.Modifiers.Any(m => m.IsKind(SyntaxKind.PublicKeyword)))
                .OrderByDescending(c => c.ParameterList.Parameters.Count)
                .FirstOrDefault();
            List<ConstructorParameterBinding> bindings = new List<ConstructorParameterBinding>();
            if (ctor is not null)
            {
                foreach (ParameterSyntax parameter in ctor.ParameterList.Parameters)
                {
                    TypeSyntax parameterType = parameter.Type ?? SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.ObjectKeyword));
                    string parameterName = parameter.Identifier.ValueText;
                    string fieldName = $"_{parameterName}";
                    bool isInterface = TypeSyntaxHeuristics.IsLikelyInterfaceType(parameterType);
                    bindings.Add(new ConstructorParameterBinding(parameterType, parameterName, fieldName, isInterface));
                }
            }
            return new ConstructorPlan(classSyntax, subjectField, bindings);
        }

        internal IEnumerable<MemberDeclarationSyntax> BuildFieldDeclarations()
        {
            foreach (ConstructorParameterBinding binding in Parameters.Where(p => p.IsInterface))
            {
                GenericNameSyntax mockGeneric = SyntaxFactory.GenericName(
                    SyntaxFactory.Identifier("Mock"),
                    SyntaxFactory.TypeArgumentList(SyntaxFactory.SingletonSeparatedList<TypeSyntax>(binding.ParameterType)));
                yield return SyntaxFactory.FieldDeclaration(
                    SyntaxFactory.VariableDeclaration(mockGeneric)
                        .AddVariables(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier(binding.FieldName))))
                    .AddModifiers(
                        SyntaxFactory.Token(SyntaxKind.PrivateKeyword));
            }
            IdentifierNameSyntax classIdentifier = SyntaxFactory.IdentifierName(ClassSyntax.Identifier);
            yield return SyntaxFactory.FieldDeclaration(
                SyntaxFactory.VariableDeclaration(classIdentifier)
                    .AddVariables(SyntaxFactory.VariableDeclarator(SyntaxFactory.Identifier(SubjectFieldName))))
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PrivateKeyword));
        }

        internal MemberDeclarationSyntax BuildInitializationMember()
        {
            BlockSyntax body = BuildInitializationBody();
            return SyntaxFactory.MethodDeclaration(
                SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)),
                "SetUp")
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                .WithBody(body)
                .WithAttributeLists(
                    SyntaxFactory.SingletonList(
                        SyntaxFactory.AttributeList(SyntaxFactory.SingletonSeparatedList(
                            SyntaxFactory.Attribute(SyntaxFactory.IdentifierName("SetUp"))))));
        }

        private BlockSyntax BuildInitializationBody()
        {
            List<StatementSyntax> bodyStatements = new List<StatementSyntax>();
            foreach (ConstructorParameterBinding binding in Parameters.Where(p => p.IsInterface))
            {
                GenericNameSyntax mockGeneric = SyntaxFactory.GenericName(
                    SyntaxFactory.Identifier("Mock"),
                    SyntaxFactory.TypeArgumentList(SyntaxFactory.SingletonSeparatedList<TypeSyntax>(binding.ParameterType)));
                ObjectCreationExpressionSyntax newMock = SyntaxFactory.ObjectCreationExpression(mockGeneric)
                    .WithArgumentList(SyntaxFactory.ArgumentList());
                StatementSyntax assignMock = SyntaxFactory.ExpressionStatement(
                    SyntaxFactory.AssignmentExpression(
                        SyntaxKind.SimpleAssignmentExpression,
                        SyntaxFactory.IdentifierName(binding.FieldName),
                        newMock));
                bodyStatements.Add(assignMock);
            }
            List<ArgumentSyntax> ctorArgs = new List<ArgumentSyntax>();
            foreach (ConstructorParameterBinding binding in Parameters)
            {
                ExpressionSyntax argumentExpression = binding.IsInterface
                    ? SyntaxFactory.MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression,
                        SyntaxFactory.IdentifierName(binding.FieldName),
                        SyntaxFactory.IdentifierName("Object"))
                    : DefaultParameterValueSyntaxFactory.CreateDefaultValueForType(binding.ParameterType);
                ctorArgs.Add(SyntaxFactory.Argument(argumentExpression));
            }
            IdentifierNameSyntax typeName = SyntaxFactory.IdentifierName(ClassSyntax.Identifier);
            ObjectCreationExpressionSyntax newSubject = SyntaxFactory.ObjectCreationExpression(typeName)
                .WithArgumentList(SyntaxFactory.ArgumentList(SyntaxFactory.SeparatedList(ctorArgs)));
            StatementSyntax assignSubject = SyntaxFactory.ExpressionStatement(
                SyntaxFactory.AssignmentExpression(
                    SyntaxKind.SimpleAssignmentExpression,
                    SyntaxFactory.IdentifierName(SubjectFieldName),
                    newSubject));
            bodyStatements.Add(assignSubject);
            return SyntaxFactory.Block(SyntaxFactory.List(bodyStatements));
        }

        private static string BuildSubjectFieldName(string className)
        {
            if (string.IsNullOrEmpty(className))
            {
                return "_targetUnderTest";
            }
            string camel = char.ToLowerInvariant(className[0]) + className.Substring(1);
            return $"_{camel}UnderTest";
        }
    }

    private sealed record ConstructorParameterBinding(
        TypeSyntax ParameterType,
        string ParameterName,
        string FieldName,
        bool IsInterface);
}
